apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
        - name: ollama
          image: alaasalmo/ollama:1.1.1.1
          ports:
            - containerPort: 11434
          resources:
            requests:
              memory: "5Gi"
              cpu: "2"
            limits:
              memory: "6Gi"
              cpu: "2"
          volumeMounts:
            - mountPath: /root/.ollama
              name: ollama-storage
      volumes:
        - name: ollama-storage
          persistentVolumeClaim:
            claimName: task-pv-claim

---
apiVersion: v1
kind: Service
metadata:
  name: ollama-service
spec:
  type: NodePort
  selector:
    app: ollama
  ports:
    - protocol: TCP
      port: 11435
      targetPort: 11434
      nodePort: 30134  # Exposes Ollama on <MinikubeIP>:30134
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-service-internal
spec:
  selector:
    app: ollama
  ports:
    - protocol: TCP
      port: 11434
      targetPort: 11434
  type: ClusterIP  # Internal cluster access only
